package.json
src/JSPyBridge/errors.py
src/JSPyBridge/proxy.py
src/JSPyBridge/pyi.py
src/pythonia/Bridge.js
src/pythonia/Bridge.py
src/pythonia/IpcPipeCom.js
src/pythonia/StdioCom.js
src/pythonia/errors.js
src/pythonia/index.js
src/pythonia/jsi.js
src/pythonia/proxy.py

* Sync bridges
* py: Custom error handling, make it friendlier/easier to debug
* js: Importing relative Python files now automatically adds the file's directory to the import path
Fixes
* js: Automatically restart Python processes on a new Python import, if python was exit()'ed earlier. Can happen in [tests](https://github.com/extremeheat/py2tsd/blob/8386e19213c35a231018e38df8d0f31bd438ec26/test/lib.test.js#L10).
* js: Fix relative imports on Windows not splitting \ correctly

js: Add dir to import path when doing local Python imports; py: Custom error handling

---

.github/workflows/python-publish.yml
HISTORY.md
README.md
examples/python/cheerio.py
examples/python/flyingsquid.py
examples/python/mineflayer.py
examples/python/nbt.py
examples/python/webserver.py
package.json
setup.py
src/JSPyBridge/errors.py
src/JSPyBridge/js/deps.js
src/JSPyBridge/proxy.py
src/__init__.py

* Fix IPython error handling
* Fix dependency manager issues
* Update readme, package data for release. Rename project to just "javascript"
* Add new bridge feature comparison table

py: Fix dep manager, rename project to "javascript"

---

.github/workflows/node.yml
.github/workflows/npm-publish.yml
.github/workflows/python-publish.yml
MANIFEST.in
examples/python/mineflayer2.py
src/__init__.py
src/javascript/__main__.py
src/javascript/connection.py
src/javascript/errors.py
src/javascript/events.py
src/javascript/js/deps.js
src/javascript/js/errors.js
src/javascript/js/pyi.js
src/javascript/proxy.py
src/javascript/pyi.py
src/pythonia/Bridge.js
src/pythonia/errors.js
src/pythonia/interface.py
src/pythonia/proxy.py

* py: errors when Python calls JS which calls Python back which returns an error is now handled
* py: do not block program exit if JS process is dead
* IO errors are suppressed. These errors are common when the other side of the bridge exists before the IO is finished on child process (e.g. crashing or Ctrl-C), no need to log them
* py: add new mineflayer example

py: Handle errors when JS calls Python, handle more IO errors

---

HISTORY.md
src/javascript/__init__.py
src/javascript/config.py
src/javascript/connection.py
src/javascript/js/bridge.js

* py: Support node.js versions 14+ or newer, account for a PR in Node.js which alters the event emitter binding code 
* https://github.com/nodejs/node/pull/35931

py: Support Node.js 14+ or newer

---

src/pythonia/index.d.ts

remove types from `python()`, not helpful and causes errors when using typescript
address #42

pythonia: Remove some type definitions

---

src/javascript/connection.py

console.log was only working if script was executed by IDLE,
Now the `subprocess.CREATE_NO_WINDOW` flag is only activated when running by IDLE to hide node console.

Fixed console.log not working in Windows

---

src/pythonia/interface.py

pythonia: use utf-8 encoding for bridging

---

src/javascript/js/bridge.js
src/javascript/js/pyi.js
src/pythonia/Bridge.js

When using the py -> js call, long strings were truncated. This commit fixes the issue by adding a buffer storing the data transmitted through stdin.

Fixing stdin String reading function that fails for long strings

---

src/pythonia/index.js

WebSocket support isn't functional, but we try to use this when a browser environment is detected (window != undefined). Since runtimes like Electron can declare window and still have access to node child_process, we can remove this check.
Fix #82

pythonia: Remove websocket comm

---

README.md
src/javascript/js/pyi.js
src/pythonia/Bridge.js

Add option to override default REQ_TIMEOUT value of 100000 ms using env vars. Configuring the timeout dynamically at runtime could be addressed in a future enhancement.
Resolves #57

Add option to configure call timeout (REQ_TIMEOUT) from env var

---

src/javascript/connection.py

Fixes #99 by checking os.environ dictionary for a custom NODE_BIN. Retains a attribute check fallback for compatibility.

javascript: check NODE_BIN in os.environ dict instead of attr

---

src/javascript/connection.py

Upon exit (in a PySide 6 project), the config.event_loop object is already set to None by the time that it hits this line in the code.
This results in an AttributeError: 'NoneType' object has no attribute 'queue' upon exit.
I patched this locally in my virtualenv and it has eliminated errors upon exit in my application.
Related to: #104

Add None check for event_loop before adding to its queue.

---

README.md
examples/python/pdfjs.py
src/javascript/connection.py
src/javascript/js/bridge.js
src/javascript/proxy.py
test/javascript/test_general.py

This is a patch that would allow to transfer binary data (e.g. Buffer) directly from Js to Py, without JSON serialization, but using the existing stderr pipe mechanism (see #67).
Example on significance:
Rendering 10 PDF pages at ~200 DPI BGRX and transferring them via the existing `bytes(js_buffer.valueOf()["data"])` takes ~35s. The new `js_buffer.blobValueOf()` added here would reduce this to ~3s. (Interestingly enough, tempfiles are actually a bit faster than `blobValueOf()`.)
----
That said, I'm rather uncertain about the implementation. Blobs can't be handled using a simple separator (such as `\n`) but need to be passed with explicit length, which breaks `stderr_lines`.
This patch changes to immediate parsing (rather than deferred on `readAll()`) so we can fetch the remainder after …

Allow to transfer binary data without serialization (CC #67)

---

src/javascript/connection.py

Reverts a change in #103 as sys.stdout.fileno doesn't exist on Colab notebooks. Also fix color outputs in notebooks.

Fix `javascript` stdout not appearing in Python on notebooks

---

src/javascript/js/deps.js

Fixes some issues with path resolution. Where as require() doesn't get updated after an npm install, it seems ESM import() does get updated, so we don't have to resolve the path manually to require it.

javascript: don't try resolving path after installation, try import() directly

---

docs/python.md
src/javascript/__init__.py
src/javascript/connection.py
src/javascript/events.py

This PR aims to solve issue #130 by creating an interface to terminate and initialize the bridge's underlying NodeJS process and threads responsible for the communication.
To do this, I moved the calls responsible for referencing the bridge classes instances to the initialization function, refactored `EventLoop` and `EventExecutorThread`'s constructors to re-initialize its properties, changed the connection logic so it does not stop upon exception or process termination, and implemented a `terminate()` function in `__init__.py`.
With this change, the following behaviour is possible:
```py
import javascript
javascript.init()
javascript.eval_js('console.log("Hello from 1st NodeJS process!")')
javascript.terminate()
javascript.init()
javascript.eval_js('console.log("Hello from 2nd NodeJS …
```

Minimal changes to allow manual re-initialization of NodeJS process

---

src/pythonia/IpcPipeCom.js
src/pythonia/interface.py

Tiny tweaks to make Python shutdown more graceful.
- `SIGTERM` rather than `SIGKILL` to allow Python `atexit` handlers, other signal handlers, and finalizers (ex. `finally`) to run before terminating.
- Added a finalization check to ensure the process doesn't try to exit while already exiting.
Without the last check, a runtime exception in the external Python triggered the following exception, caused because the `json` module is not guaranteed to still exist in the namespace :
```
Exception ignored in: <function Proxy.__del__ at 0x79bf799404c0>
Traceback (most recent call last):
File "node_modules/pythonia/src/pythonia/proxy.py", line 226, in __del__
File "node_modules/pythonia/src/pythonia/proxy.py", line 111, in free
File "node_modules/pythonia/src/pythonia/Bridge.py", line 273, in …
```

fix: more graceful python shutdown

---

.gitignore
README.md
src/javascript/js/pyi.js
src/javascript/proxy.py
src/pythonia/Bridge.js
src/pythonia/proxy.py

* Fix the `.new` python pseudo method to instantiate ES5 classes incorrectly passing prop FFID as opposed to current FFID
* fix #136 
* Allow setting REQ_TIMEOUT to 0 to disable timeout checks

Fix ES5 class handling, allow disabling timeouts

---

src/pythonia/index.d.ts

Ensure that functions such as `python.exit()` are typed in typescript.

Add properties to pythonia ts types

---

src/javascript/js/bridge.js
src/pythonia/jsi.js
test/javascript/test.js

.stack may not exist so just stringify the whole error object

Handle non-Error objects thrown in JS

---

README.md

I'd usually split the long lines into multiple to facilitate git diff/merge workflows. Having shorter lines would have made my diff more obvious. Shall I?

Readme § Limitations: Fix some typos, optimize wording.

---

src/javascript/js/deps.js

To get npm package names for installing during first time from require statements with file paths.
Example
```js
require('mathjax-full/es5/tex-svg.js')
```

fix: npm package name resolution when using require with file paths from npm modules.
